### ISSUE TITLE
about  preprocessing

### ISSUE THREAD

**Issue by ruanruan0518** [NSSL-SJTU/HermesSim#10]
When I try to use a new dataset following the steps you provided, is there a part of the script missing?
Traceback (most recent call last):
  File "/home/ruan/HermesSim-main/preprocess/preprocessing_pcode.py", line 478, in <module>
    main()
  File "/home/ruan/anaconda3/envs/hermessim/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ruan/anaconda3/envs/hermessim/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ruan/anaconda3/envs/hermessim/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ruan/anaconda3/envs/hermessim/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ruan/HermesSim-main/preprocess/preprocessing_pcode.py", line 461, in main
    str_dict, pkl_dict = create_functions_dict(
  File "/home/ruan/HermesSim-main/preprocess/preprocessing_pcode.py", line 394, in create_functions_dict
    for idb_path, str_func_one, pkl_func_one in \
  File "/home/ruan/anaconda3/envs/hermessim/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/ruan/HermesSim-main/preprocess/preprocessing_pcode.py", line 358, in process_one_file
    f_list = create_features_matrix(
  File "/home/ruan/HermesSim-main/preprocess/preprocessing_pcode.py", line 312, in create_features_matrix
    opcs[i] = opc_dict[ty]
KeyError: 'libcrypto.so.1.0.0_NETGEAR_R7000_1.0.2h_arm32_acfg_disasm.js_reg'

1、I can not find how to precess opcodes_dict.json
2、I use the pcode_lifter.py to precess and then I find 【"0x4a98c":{"PcodeLevel":"normalize","TSCG":{"nodes":[2,60,8,31,83,4,32,19,64,36,12,55,18,62,11,38,15,59,17,34,87,10,6,72,85,57,30,48,9,81,74,13,50,70,53,52,42,26,28,29,61,22,16,23,37,1,46,33】different from【at.i64":{"0x54800":{"PcodeLevel":"raw","TSCG":{"nodes":[6748,6576,6712,6653,6657,6511,6806,6593,6553,6644,6585,6760,6632,6650,6622,6516,6514,6746,6774,6506,6818,6771,6766,6718,6558,6708,6655,6570,6620,6581,6651,6640,6595,6618,6744,6814,6789,6738,6642,6508,6574,6597,6724,6679,6580,6832,6530,6803,6628,6573,6543,6710,6539,6567,6811,6541,6660,6560,6742,6537,6662,6586,6691,6675,6658,6520,6607,6515,6701,6813,6703,6693,6720,6758,6588,6552,6799,6706,6752,6773,6545,6816,6741】you provide

**Comment by sgfvamll** [comment]
The produced JSON file should look like this: `{"x64-gcc-7-O1_curl":{"0x3b20f8":{"nodes":[0,1,5,6,2,4,3],"nverbs":{"0":["END"],"1":["RET"],`. I am not sure why yours misses the top key (e.g., the `"x64-gcc-7-O1_curl":` or `"xxat.i64":`). Maybe you should try fixing it first. 
We cannot guarantee that all scripts will work directly on other datasets. However, there should only be some minor bugs.

**Comment by ruanruan0518** [comment]
I mean the preprocessing_pcode.py need opcodes_dict.json，I did not find how to process it.

**Comment by sgfvamll** [comment]
> I mean the preprocessing_pcode.py need opcodes_dict.json，I did not find how to process it.

Then you need to follow this file: [preprocess_all.sh](https://github.com/NSSL-SJTU/HermesSim/blob/main/preprocess/preprocess_all.sh). 

Remember to add the `--training` option when processing the training set.

**Comment by cong0221** [comment]
> When I try to use a new dataset following the steps you provided, is there a part of the script missing? Traceback (most recent call last): File "/home/ruan/HermesSim-main/preprocess/preprocessing_pcode.py", line 478, in main() File "/home/ruan/anaconda3/envs/hermessim/lib/python3.10/site-packages/click/core.py", line 1130, in **call** return self.main(*args, **kwargs) File "/home/ruan/anaconda3/envs/hermessim/lib/python3.10/site-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/home/ruan/anaconda3/envs/hermessim/lib/python3.10/site-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/ruan/anaconda3/envs/hermessim/lib/python3.10/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/home/ruan/HermesSim-main/preprocess/preprocessing_pcode.py", line 461, in main str_dict, pkl_dict = create_functions_dict( File "/home/ruan/HermesSim-main/preprocess/preprocessing_pcode.py", line 394, in create_functions_dict for idb_path, str_func_one, pkl_func_one in File "/home/ruan/anaconda3/envs/hermessim/lib/python3.10/site-packages/tqdm/std.py", line 1195, in **iter** for obj in iterable: File "/home/ruan/HermesSim-main/preprocess/preprocessing_pcode.py", line 358, in process_one_file f_list = create_features_matrix( File "/home/ruan/HermesSim-main/preprocess/preprocessing_pcode.py", line 312, in create_features_matrix opcs[i] = opc_dict[ty] KeyError: 'libcrypto.so.1.0.0_NETGEAR_R7000_1.0.2h_arm32_acfg_disasm.js_reg'
> 
> 1、I can not find how to precess opcodes_dict.json 2、I use the pcode_lifter.py to precess and then I find 【"0x4a98c":{"PcodeLevel":"normalize","TSCG":{"nodes":[2,60,8,31,83,4,32,19,64,36,12,55,18,62,11,38,15,59,17,34,87,10,6,72,85,57,30,48,9,81,74,13,50,70,53,52,42,26,28,29,61,22,16,23,37,1,46,33】different from【at.i64":{"0x54800":{"PcodeLevel":"raw","TSCG":{"nodes":[6748,6576,6712,6653,6657,6511,6806,6593,6553,6644,6585,6760,6632,6650,6622,6516,6514,6746,6774,6506,6818,6771,6766,6718,6558,6708,6655,6570,6620,6581,6651,6640,6595,6618,6744,6814,6789,6738,6642,6508,6574,6597,6724,6679,6580,6832,6530,6803,6628,6573,6543,6710,6539,6567,6811,6541,6660,6560,6742,6537,6662,6586,6691,6675,6658,6520,6607,6515,6701,6813,6703,6693,6720,6758,6588,6552,6799,6706,6752,6773,6545,6816,6741】you provide

I encountered the same error, but my JSON file was generated correctly. The error occurs because the `arch` variable is extracted from the filename. Simply adding the architecture information at the beginning of the JSON filename can resolve the issue. For example, rename
`libcrypto.so.1.0.0_NETGEAR_R7000_1.0.2h_arm32_acfg_disasm.json`
to
`arm32-libcrypto.so.1.0.0_NETGEAR_R7000_1.0.2h_arm32_acfg_disasm.json`.
