### ISSUE TITLE
IDA Pro or Ghidra for disassembly 

### ISSUE THREAD

**Issue by Emegua** [NSSL-SJTU/HermesSim#11]
Thanks for making your work public! 

I read the following statement in the paper: "We utilize Ghidra to disassemble binary functions and lift them to its Pcode IR, based
on which we then construct the SOG," but the data processing pipeline in the repo uses IDA Pro for that. I'd like to know if I missed something.  

Thanks

**Comment by sgfvamll** [comment]
Please also note that, 
> This dataset relies on IDA Pro 7.3 [35] to recover the control flow and the boundaries of basic blocks and then uses Capstone [34] to disassemble the raw bytes of each basic block. To minimize the potential impact of underlying disassembly capabilities, we use the control flow and the boundaries of the basic blocks presented in the original dataset, relying only on Ghidra to disassemble the raw bytes of each basic block.
> -- Section 5.1 

We did "utilize Ghidra to disassemble binary functions and lift them to its Pcode IR". However, some steps (e.g., control flow recovery) in the pre-processing of this dataset involve IDA Pro.

**Comment by Emegua** [comment]
Thanks for your fast response. But I found this two confusing: "... uses Capstone [34] to disassemble the raw bytes of each basic block." and "relying only on Ghidra to disassemble the raw bytes of each basic block."

And is the script that you used to disassemble the raw bytes of each basic block using Ghidra available in the repository? I couldn't locate it.

**Comment by sgfvamll** [comment]
The original dataset uses Capstone. We use Ghidra as SOG is based on the PCode IR. 
For the script to disassemble the raw bytes and to lift code to SOG, please refer to this [part](https://github.com/NSSL-SJTU/HermesSim?tab=readme-ov-file#1-lifting-binary-functions-pcode-based-representations) in the README.md. This part invokes the [GSAT](https://github.com/sgfvamll/gsat) to conduct the major work.
