### ISSUE TITLE
Source code for gsat-1.0.jar

### ISSUE THREAD

**Issue by Jialong-Zhu** [NSSL-SJTU/HermesSim#14]
Hi authors, thank you for publishing such excellent work!
Would you consider publishing the source code for building the pcode-based graphs (gsat-1.0.jar) to facilitate relevant graph studying？
Sincerely, many thanks!!

**Comment by sgfvamll** [comment]
The source code of gsat-1.0.jar is published at https://github.com/sgfvamll/gsat
The link in the Readme points to the release page of this repo.
