### ISSUE TITLE
model/configures中的配置

### ISSUE THREAD

**Issue by SergioOvO** [NSSL-SJTU/HermesSim#15]
首先非常感谢您开源了如此详细的代码。
请问能否添加一些说明，描述model/configures中的不同配置文件的作用？例如使用哪些模型/做哪些实验等。另外想知道哪个配置是本文模型所使用的。

**Comment by sgfvamll** [comment]
你看一下配置文件的内容，对照论文，里面有哪些实验应该是很显然的。
关于文本模型的代码，你可以参考相关论文开源的仓库。这个仓库只开源了我们自己模型的代码以及和图神经网络的对比实验、消融实验。
