### ISSUE TITLE
Some questions about /inputs/*.pkl

### ISSUE THREAD

**Issue by xhh-an** [NSSL-SJTU/HermesSim#16]
您好，我尝试在学习您的preprocess过程中，对于生成过程发现了一些小问题，还希望得到您的回复，感激不尽！
为了学习您的算法,我尝试挑选了一个较小的代码进行学习，选取了/Dataset-1/openssl/x64-gcc-7-Os_ossltest.so文件,里面的在0x27aa处的函数<bind_engine>。然后我对其手动进行gsat模块的生成和preprocess过程,最后得到了一个inputs的.pkl文件。
在这里我生成了一个pkl文件有一个函数信息，包括的是graph(就是那个5tuple,两个edge index,一个edge feat,两个node size)和opc(node的embedding),这里显示的是我有58个结点和96条边.我使用的java命令是"pcode-extractor-v2 -m elf -f ./graph/x64-gcc-7-Os_ossltest.so -c ./graph/x64-gcc-7-Os_ossltest.so_cfg_summary.json -of ALL -v 1 -opt 1 -o ./graph/ALLPUT1.json"
但是我试图去访问您的inputs文件夹提供的pkl文件(现成的数据集),我尝试访问inputs/pcode_raw/pcode_sog?Dataset-1_training/graph_func_dict_opc_55.0.pkl的obj=obj['IDBs/Dataset-1/openssl/x64-gcc-7-Os_ossltest.so.i64']['0x27aa']的时候,发现里面这个graph的size大概是有129个结点和218个边左右，这和我自己生成的size不同。
而经过我观察，这个size大概是和-opt 0是差不多的。
所以想再此问一下，您生成inputs数据集的时候是使用-opt 0生成的吗?如果是的话,用-opt 1进行训练会有什么问题吗?另外我看lifting文件夹中的提取脚本,它默认的是-opt 1而不是0.
期待您的回复！！

**Comment by sgfvamll** [comment]
我们的数据应该是 -opt 0 生成的。opt 是 optimization 的缩写，表示是否开启 Ghidra 自带的反编译器的优化选项，优化后pcode图的大小会更小，但可能会引入一些错误，以及会有部分函数无法成功反编译（这部分函数应该会回退到 -opt 0 进行处理）。
我们实验过 -opt 0 和 -opt 1，发现引入 Ghidra 反编译优化后的优化效果没有变得更好，反而显著增加了反编译时间和错误率。论文里由于篇幅没有报告这个实验的结果。
应该是因为先跑了 -opt 0 ，后跑 -opt 1 导致代码里残留的默认值是 -opt 1 。发布时没有注意到这处问题，非常感谢提出。
