### ISSUE TITLE
作者您好，关于二进制文件提升部分的问题

### ISSUE THREAD

**Issue by kaikai145154** [NSSL-SJTU/HermesSim#17]
作者您好，在二进制文件提升部分，我使用您打包好的gsat-1.0.jar工具和lifting/pcode_lifter.py脚本重新生成了Dataset-1/features/testing/pcode_raw_Dataset-1_testing下的*_acfg_disasm.json文件，但与您发布的文件相比每个字段都有一些出入（如下图所示），想请问一下您这是因为什么呢？如果我用重新生成的这些文件训练模型会导致结果有较大差异吗？
![6a0cf6d9-d933-46e9-829e-a01dd663ea4f](https://github.com/user-attachments/assets/a1078ce9-01f6-4635-9fd0-54da8a92ecb7)
![8C7D3685B74F4AB1CE4D9AB8EB4CABB6](https://github.com/user-attachments/assets/e9fa1124-4bbe-4661-8503-6a818b80765e)

**Comment by kaikai145154** [comment]
图1是您发布的文件，图2是我自己生成的文件

**Comment by sgfvamll** [comment]
应该是Ghidra内部某些地方有一些随机性，看起来主要是node的id值不同。结果应该不会有太大差异。

**Comment by kaikai145154** [comment]
好的，我刚刚使用重新生成的文件训练了模型，模型性能是差不多的。谢谢您的回复
