### ISSUE TITLE
please answer this problem,thanks!

### ISSUE THREAD

**Issue by twythebest** [NSSL-SJTU/HermesSim#18]
I apologize for the interruption. Regarding the testing portion of the code using the file \HermesSim-main\dbs\Dataset-1\testing_Dataset-1.csv, I encountered an issue where the file does not possess the 'groups' attribute. Consequently, the following statement in the file \HermesSim-main\model\core\graph_factory_testing.py:

```python
self._group_ids = np.array([r['group'] for _, r in self._func_info.iterrows()])
```

generates an error.

**Comment by sgfvamll** [comment]
GraphFactoryTesting is used to load the validation dataset. If you want to use it to load the test dataset (maybe you want to run validation metrics on the test dataset), you can add a 'group' column to testing_Dataset-1.csv by assigning the same group id to functions with the same symbol name and the different group id to functions with different names.
