### ISSUE TITLE
I can't rebuild the flowchart_Dataset-1.csv file without IDA pro?

### ISSUE THREAD

**Issue by Daocuong-main** [NSSL-SJTU/HermesSim#2]
I'm trying to apply my data set to your method, but when building the dbs folder, I realized I need to file a flowchart_Dataset-1.csv file like yours. To have that file, I see that according to the instructions you need IDA pro, so if you don't have it, we can't apply our data to your method, right?

**Comment by sgfvamll** [comment]
`flowchart_Dataset-*.csv` can also be generated using other decompilers like Ghidra. However, you may need to write the script yourself (by mimicking the IDA script), as we have no plans to support it at this time.

**Comment by sgfvamll** [comment]
We now publish [a new version of gsat](https://github.com/sgfvamll/gsat/releases) that supports generating cfg files directly without a flowchart file.
