### ISSUE TITLE
initial vector

### ISSUE THREAD

**Issue by zzjss12** [NSSL-SJTU/HermesSim#5]
How did the initial vector of each node in the graph come from

**Comment by sgfvamll** [comment]
Please refer to these sections in the README: [1-lifting-binary-functions-pcode-based-representations](https://github.com/NSSL-SJTU/HermesSim?tab=readme-ov-file#1-lifting-binary-functions-pcode-based-representations), and [2-preprocess-inputs](https://github.com/NSSL-SJTU/HermesSim?tab=readme-ov-file#2-preprocess-inputs).
