### ISSUE TITLE
model training

### ISSUE THREAD

**Issue by yyhhxx** [NSSL-SJTU/HermesSim#6]
When training the model, `/Dataset-1/pairs/validation/validation_functions.csv` is used. How is this file generated? The step of lifting and preprocess didn't generate such file.

**Comment by sgfvamll** [comment]
Please refer to the previous work [binary_function_similarity](https://github.com/Cisco-Talos/binary_function_similarity).

**Comment by yyhhxx** [comment]
Sorry, I didn't found scrips to generate it. This file path is used in https://github.com/NSSL-SJTU/HermesSim/blob/a8fee0d218519826dd4a7a9799077effa40e5cb1/model/core/config.py#L134. But after running  `binary_function_similarity/blob/main/DBs/Dataset-1/Dataset-1 creation.ipynb`, I only got the following files in the `pairs` folder：
│    └── validation
│        ├── neg_validation_Dataset-1.csv
│        └── pos_validation_Dataset-1.csv

**Comment by sgfvamll** [comment]
Sorry, I thought that you were asking about another file previously. 
I indeed forgot to upload the script to generate this file. 
The `/Dataset-1/pairs/validation/validation_functions.csv` actually contains only a list of all functions in the validation dataset. And the binary functions with the same function symbol are assigned with the same group ID. 
( I will try to find this script and upload it later... )
