### ISSUE TITLE
Error: Unable to access jarfile bin/gsat-1.0.jar

### ISSUE THREAD

**Issue by iyuer1118** [NSSL-SJTU/HermesSim#7]
When I ran lifting/pcode_lifter.py, I found that the processing of all files failed. When I went to debug, I discovered that the program encountered an error while executing the following command. The specific command and error are as follows:

Command:
`java -ea -Xmx16G -XX:+UseCompressedOops -jar bin/gsat-1.0.jar pcode-extractor-v2 -m elf         -f binaries/Dataset-1/nmap/arm32-gcc-4.8-Os_nping -c dbs/Dataset-1/cfg_summary/testing/arm32-gcc-4.8-Os_nping_cfg_summary.json -of ALL -v 1        -opt 1 -o ./dbs/Dataset-1/features/testing/pcode_raw_Dataset-1_testing/arm32-gcc-4.8-Os_nping_acfg_disasm.json bin/gsat-1.0.jar`

Error:
`Unable to access jarfile bin/gsat-1.0.jar`

Could you please provide the file "bin/gsat-1.0.jar", or let me know how to obtain this file?

**Comment by sgfvamll** [comment]
Please refer to this section [README](https://github.com/NSSL-SJTU/HermesSim?tab=readme-ov-file#artifacts) for all artifacts.
